
version: 2

models:
  - name: agg_genre_ratings
    description: Aggregated ratings by movie genre
    columns:
      - name: movie_genre
        description: The genre of the movie
      - name: total_movies
        description: The total number of movies in this genre
      - name: avg_rating
        description: The average rating for movies in this genre


